--CREATE USER MY_USER FOR LOGIN MY_LOGIN

USE [MyDB]
IF NOT EXISTS(SELECT * FROM sys.database_principals WHERE name = N'MY_USER')
BEGIN
	CREATE USER MY_USER FOR LOGIN MY_LOGIN
	--ALTER ROLE db_owner {ADD MEMBER EDDSDBO} –-SQL2012+
	EXEC sp_addrolemember 'db_owner', 'MY_USER'
END

